# Generated by Django 4.1.4 on 2023-01-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
